### ISSUE TITLE
GrafanaでAWS CloudWatch Syntheticsのメトリクスを取れるようにする

### ISSUE THREAD

**Issue by oke-py** [cloudnativedaysjp/dreamkast-infra#1055]
devにダッシュボードはあるが、No dataとなっている。
https://grafana.com/grafana/dashboards/13892

https://docs.aws.amazon.com/ja_jp/AmazonCloudWatch/latest/monitoring/CloudWatch_Synthetics_Canaries_Roles.html

**Comment by inductor** [comment]
本番でも取れてるのでClose
