### ISSUE TITLE
GrafanaをRollingUpdateしようとするとMulti-Attach error for volumeとなって進まない

### ISSUE THREAD

**Issue by oke-py** [cloudnativedaysjp/dreamkast-infra#1056]
deployment/grafanaをRollingUpdateしようとすると、現PodがVolumeをつかんでいて新Podにattachできない。
ref https://github.com/grafana/helm-charts/issues/146

`deploymentStrategy: { "type": "Recreate" }`にしたい。`persistence.type: statefulset`でもよさそう。

> FailedMount
> Unable to attach or mount volumes: unmounted volumes=[storage], unattached volumes=[config dashboards-default storage kube-api-access-7pmf2]: timed out waiting for the condition

> FailedMount
> Unable to attach or mount volumes: unmounted volumes=[storage], unattached volumes=[storage kube-api-access-7pmf2 config dashboards-default]: timed out waiting for the condition

> FailedMount
> Unable to attach or mount volumes: unmounted volumes=[storage], unattached volumes=[dashboards-default storage kube-api-access-7pmf2 config]: timed out waiting for the condition

> FailedAttachVolume
> Multi-Attach error for volume "pvc-86994706-bcae-4bce-897f-13b70b0a59f1" Volume is already used by pod(s) grafana-778f96f899-98mqq

![rollingupdate](https://user-images.githubusercontent.com/4710215/137625985-5ea35134-0c10-4d54-962b-90a65cb8b11e.png)
![events](https://user-images.githubusercontent.com/4710215/137625998-e0a3c2d2-7ec2-4914-a6cb-06526afc202d.png)

**Comment by oke-py** [comment]
ローカル環境では以前も発生していた。現Podをdeleteすると新Podが隙きを見て立ち上がるという怪しげなことをしていた。
devとprodでは今まで問題なかったのだろうか？

**Comment by inductor** [comment]
StatefulSetでいいんじゃないかな。
