### ISSUE TITLE
IVS/MediaLiveのメトリクスダッシュボードがほしい

### ISSUE THREAD

**Issue by takaishi** [cloudnativedaysjp/dreamkast-infra#1143]

**Comment by inductor** [comment]
CloudWatch metricsでIVSのConcurrent ViewとMedia Liveのネットワーク帯域あたりは取れることが分かっている

**Comment by oke-py** [comment]
「ウィジェットの追加」
![add-widget](https://user-images.githubusercontent.com/4710215/139586324-a3032cce-bdba-4838-a7e9-f8641b511459.png)

「線」を選択して「次へ」（線以外を使う場合もあるかも）
![line](https://user-images.githubusercontent.com/4710215/139586372-09afc2f8-0148-4ddc-98d7-a90c82227e9f.png)

「メトリクス」を選択して「設定」
![metrics](https://user-images.githubusercontent.com/4710215/139586438-47e57424-0309-4f42-a713-3d99643a4468.png)

「MediaLive」または「IVS」を選択（以下、MediaLiveを例として説明）
![all-metrics](https://user-images.githubusercontent.com/4710215/139586519-60215f80-d1e2-4db6-adef-b99a7fd0f213.png)

「ChannelId, Pipeline」を選択
![channelid-pipeline](https://user-images.githubusercontent.com/4710215/139586588-1e7fb615-ea98-4b00-beef-b62bef682639.png)

検索で絞ってメトリクスを選択、グラフタイトルを入力して「ウィジェットの作成」
![select-metrics](https://user-images.githubusercontent.com/4710215/139586658-4ca90a41-39ef-4f01-8485-3fe5f7a08bc7.png)

「グラフ化したメトリクス」を選択して「ラベル」を編集
Channel IDとNameの対応はこちらで確認できる。
https://console.aws.amazon.com/medialive/home?region=us-east-1#!/channels
![edit-label](https://user-images.githubusercontent.com/4710215/139586837-118813e5-4d90-4abd-94cc-cae92d7044da.png)

**Comment by oke-py** [comment]
グラフによって凡例の並び、色がばらばらになることがある。
グラフの編集で「発信元」のJSONを並び替えるとよし。

**Comment by oke-py** [comment]
完了
