### ISSUE TITLE
GrafanaがRDSのメトリクスをとれてない

### ISSUE THREAD

**Issue by takaishi** [cloudnativedaysjp/dreamkast-infra#1187]
らしい。

https://cloudnativedays.slack.com/archives/C015CN1PQ06/p1636000139345800

**Comment by inductor** [comment]
これ多分CloudWatch Datasourceごと動いてなさそうな気配があるのでなんとかしたいですね早めに

@kntks @ryojsb あたりとったりできませんか！

**Comment by kntks** [comment]
RDSのcluster metricsのパネルはRDSのクラスターが存在しないので、データも存在しないだけかな・・？
```
$ aws rds describe-db-clusters --profile dreamkast --region ap-northeast-1
{
    "DBClusters": []

}
```
DimensionsがDBClusterIdentifierになっていてデータが存在しないので、パネルが `No data`になっている
![スクリーンショット 2021-12-04 0 20 33](https://user-images.githubusercontent.com/24477226/144627139-fe46c550-dd4d-4f59-b433-c6dd738393a6.png)

**Comment by kntks** [comment]
dockerのGrafanaイメージを使って立ち上げると、ちゃんとメトリクスが取れる・・

**Comment by kntks** [comment]
もう1週間粘ってみます！

**Comment by kntks** [comment]
ローカル環境でv8.2.3 -> v8.2.4にバージョンを上げると事象が解消しました
https://github.com/grafana/grafana/releases?page=2

2021-11-03 (v8.2.3 ) ~  2021-11-15 (v8.2.4) のpull requestに理由があるはず
https://github.com/grafana/grafana/compare/v8.2.3...v8.2.4#
https://github.com/grafana/grafana/pulls?page=1&q=is%3Apr++merged%3A2021-11-03..2021-11-15+label%3A%22type%2Fbug%22

しかし、fixしたpull requestがすぐに見当たらなかったのと、現状治っているので保留にしている

**Comment by jacopen** [comment]
12/26のミーティングで、この件は解消したということで閉じ
