### ISSUE TITLE
各コンポーネントのリリースに気付ける仕組みを導入する

### ISSUE THREAD

**Issue by oke-py** [cloudnativedaysjp/dreamkast-infra#1189]
#1171 のようにイベントごとに総チェックするだけでなく、早めに気付けるようにもしておきたい。脆弱性対応などに備えて。

dependabotやrenovateが使えればいいが、パッケージマネージャーで管理しているわけではないため厳しそう。
Slackに各GitHubリポジトリの`releases`通知を受け取るぐらいしか思いつかないし、それで十分な気がする。

```
/github subscribe grafana/helm-charts releases
/github unsubscribe grafana/helm-charts issues pulls commits deployments
```
たいした手間ではないが、一発で`releases`のみsubscribeできないのかな。

**Comment by ryojsb** [comment]
RSSをチャネルに飛ばすようにする。

◯ Channel名
@oke-py さんどうしましょう。

◯ target

- ArgoCD
- Contour
- cert-manager
- prometheus
- grafana
- loki

@oke-py さん、他に何かありますでしょうか。

**Comment by inductor** [comment]
#dreamkast-maintenance-notification
とか？（しらんけど

**Comment by oke-py** [comment]
watchしているリポジトリをとってきました。jarger watchしてなかった。
- argoproj-labs/argocd-notifications
- argoproj/argo-cd
- aws/eks-charts
- external-secrets/kubernetes-external-secrets
- grafana/grafana
- grafana/helm-charts
- grafana/loki
- jetstack/cert-manager
- kubernetes-sigs/metrics-server
- projectcontour/contour
- prometheus-operator/prometheus-operator
- prometheus/node_exporter
- prometheus/prometheus

**Comment by ryojsb** [comment]
@oke-py @inductor 
設定をしましたので、一旦様子を見れればと思います。
![image](https://user-images.githubusercontent.com/36046682/145421489-17571255-7dec-48df-9d34-2284255c7765.png)

**Comment by oke-py** [comment]
ありがとうございました！
