### ISSUE TITLE
Bump prometheus from v2.26.0 to v2.31.1

### ISSUE THREAD

**Issue by oke-py** [cloudnativedaysjp/dreamkast-infra#1224]
subtask of #1171
ref #1222 

修正対象はこのファイルのみだったかと思います。
https://github.com/cloudnativedaysjp/dreamkast-infra/blob/main/manifests/infra/prometheus/base/prometheus.yaml

マニフェストを自前で持たず、このあたりをそのまま使うこともできそうです。その場合は2.29.1止まりですが。
https://github.com/prometheus-operator/kube-prometheus/blob/v0.9.0/manifests/prometheus-prometheus.yaml

**Comment by mayocream** [comment]
ref: https://github.com/cloudnativedaysjp/dreamkast-infra/pull/1237#issuecomment-981627094

After applying #1237 
![image](https://user-images.githubusercontent.com/35420264/143877564-1986ba36-4345-4dbf-ba79-72aff1e444b0.png)
![image](https://user-images.githubusercontent.com/35420264/143877619-20247e4c-ec58-48ef-aa5c-ebc11e687c93.png)
It's running without errors.
