### ISSUE TITLE
Bump node-exporter from v1.1.2 to v1.2.2 or v1.3.0

### ISSUE THREAD

**Issue by oke-py** [cloudnativedaysjp/dreamkast-infra#1225]
subtask of #1171
ref #1222

修正対象
https://github.com/cloudnativedaysjp/dreamkast-infra/blob/main/manifests/infra/prometheus/base/node-exporter.yaml
https://github.com/cloudnativedaysjp/dreamkast-infra/blob/main/manifests/infra/prometheus/base/monitor.yaml#L10

マニフェストを自前で持たず、このあたりをそのまま使うこともできそうです。
https://github.com/prometheus-operator/kube-prometheus/tree/v0.9.0/manifests
node-exporter-*.yaml

**Comment by mayocream** [comment]
After applying #1236
![image](https://user-images.githubusercontent.com/35420264/143878157-eb8a3359-0994-4acf-b78a-a9d83781c7f9.png)
Seems good (dev).
