### ISSUE TITLE
AWSのコストについて可観測性を高めたい

### ISSUE THREAD

**Issue by takaishi** [cloudnativedaysjp/dreamkast-infra#1249]
ダッシュボードやDaily or Weeklyでレポートするなどして、今いくらかかっているのか、予算に対してどうなのかなどを関係者が把握できるようにしたい。

**Comment by kntks** [comment]
以下のダッシュボードを入れれば確認できそう
https://grafana.com/grafana/dashboards/139

> Daily or Weeklyでレポートする

は実現方法調査中です！

**Comment by jacopen** [comment]
これ完了してるのでおわりー！
