### ISSUE TITLE
Prometheusのメトリクス保持期間をいい感じに長くする

### ISSUE THREAD

**Issue by oke-py** [cloudnativedaysjp/dreamkast-infra#1252]
`storage.tsdb.retention.time`が`1d`となっているため、いい感じに長くする。
適切な値はObservabilityチームがやりたいこと次第か。

![flags](https://user-images.githubusercontent.com/4710215/143732223-4f77e008-5b49-40d9-94f5-e06456606c63.png)

**Comment by ShotaKitazawa** [comment]
これもやりたいこと次第ですが、別 issue として、適当にサンプリングしたメトリクスを完全に永続化するためのremote_write 先を用意してやっても良いかもですね。

そうすれば、イベントが終わった後も「イベント当日のメトリクスはこんな感じでした」をずっと見せることが出来たりできるかなあと思ってます

**Comment by oke-py** [comment]
#1253 かと思いましたが、サンプリングはまた別の話ですかね。

**Comment by ryojsb** [comment]
> これもやりたいこと次第ですが、別 issue として、適当にサンプリングしたメトリクスを完全に永続化するためのremote_write 先を用意してやっても良いかもですね。

こちらに関して、ThanosやVictoriaMetricsあたりの検証をしますか？

**Comment by oke-py** [comment]
fixed by #1297 (only production)
