### ISSUE TITLE
prometheuses.monitoring.coreos.comのmetadata.annotationが長すぎてSyncFailedとなる

### ISSUE THREAD

**Issue by oke-py** [cloudnativedaysjp/dreamkast-infra#1255]
> CustomResourceDefinition.apiextensions.k8s.io "prometheuses.monitoring.coreos.com" is invalid: metadata.annotations: Too long: must have at most 262144 bytes

![syncfailed](https://user-images.githubusercontent.com/4710215/143734547-8d6164d1-8522-41c4-be1d-f526d82461be.png)

公式は`kubectl apply`ではなく`kubectl create`せよと言っています。
https://github.com/prometheus-operator/prometheus-operator/issues/4355

そう言われてもArgoCDでどうすればいいのか、というのは https://github.com/prometheus-community/helm-charts/issues/1500#issuecomment-968892923 で解決しそうです。
> For ArgoCD you can add the annotation argocd.argoproj.io/sync-options: Replace=true to the CRD

**Comment by oke-py** [comment]
It works fine!
<img width="960" alt="argocd-dev-prometheus" src="https://user-images.githubusercontent.com/4710215/143863522-4906520a-bcdf-4248-858e-70e23a6e411c.png">

**Comment by mayocream** [comment]
> It works fine!
> 
> <img width="960" alt="argocd-dev-prometheus" src="https://user-images.githubusercontent.com/4710215/143863522-4906520a-bcdf-4248-858e-70e23a6e411c.png">
> 
> 

Nice!
