### ISSUE TITLE
migrate of synthetics monitoring service

### ISSUE THREAD

**Issue by ShotaKitazawa** [cloudnativedaysjp/dreamkast-infra#1260]
### Description

We're currently using CloudWatch Synthetics for end-to-end monitoring.

However, because CloudWatch Synthetics is expensive, we need to consider alternative solutions.

### Todo in this issue

- investigate some synthetics monitoring services.
- migrate to new synthetics monitoring service with the same functionality/configuration as we have now

**Comment by inductor** [comment]
英語なおした

**Comment by jacopen** [comment]
DkのMLでUptime Robotのアカウント作った

https://uptimerobot.com/

**Comment by jacopen** [comment]
## Uptime Robot
https://uptimerobot.com/

Pricing
https://uptimerobot.com/pricing/

- Free
- Pro $15/month

**Comment by ShotaKitazawa** [comment]
Uptime Robot is LGTM.

There are exporter & dashboard for Uptime Robot. 

* https://github.com/lekpamartin/uptimerobot_exporter
* https://grafana.com/grafana/dashboards/9955

I create other PR to install exporter & dashboard, and close this issue.
