### ISSUE TITLE
メトリックの収集に使っているGrafana、Prometheusのディスクサイズ検討

### ISSUE THREAD

**Issue by inductor** [cloudnativedaysjp/dreamkast-infra#1265]
いまいまはデフォの値から決め打ちしてるけどそれでよさそうか検討したい

**Comment by ryojsb** [comment]
#1276 にも付随しますが、
まず以下がPrometheusで、pvcの使用率的には700MiB程度あれば現状対応できそうです。
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/36046682/144738981-15fdba9c-a9cd-423f-a46a-00b8ff712b55.png">

次にGrafanaですが50MiBで足ります。
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/36046682/144738999-b1973dc3-a2df-4b3b-afca-ef9660127e84.png">

Lokiに関しては、最大値が取れておらず現状上昇中です。
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/36046682/144739024-c5001070-2c1d-4c5e-b23d-e286c2405e48.png">

**Comment by iaoiui** [comment]
Prometheusのディスク容量ですが、200MB/4h(約1.2GB/1日)くらいの感覚で増えているんですね
o11yconの会期(3/11) + 1ヶ月程度保持するとすると、現時点(12/15)からだと120日程度のretentionになってきそうです。
1年保持したい要件なども別途出てきそうですが、o11ycon会期後に改めてretentionの相談できると良さそうです

これから取得するメトリクスもあると思いますが、120日のretentionが嬉しいかもという数値だけ一旦共有です

**Comment by mhoshi-vm** [comment]
> 120日のretentionが嬉しいかもという数値だけ一旦共有です

これにいったん同意です。どうしてもコスト的な問題があるのであれば、
- もうひとつPrometheus を立てて
- remote_write + 専用のTag で必要なメトリクスのみ長期保管
みたいな方法もありますが、使い勝手は単純に大きくするが絶対にいいかと、、、
