### ISSUE TITLE
grant Editor permissions on Grafana to o11y team, Viewer permissions on registrants

### ISSUE THREAD

**Issue by oke-py** [cloudnativedaysjp/dreamkast-infra#1279]
grant permissions on Grafana

* Dreamkast team: Admin
* Observability team: Editor
* registrants: Viewer

> There are three types of permissions:
> 
> * Permissions granted as a Grafana Server Admin
> * Permissions associated with your role in an organization
> * Permissions granted to a specific folder or dashboard
> 
> You can be granted permissions based on:
> 
> * Grafana Server Admin status.
> * Organization role (Admin, Editor, or Viewer).
> * Folder or dashboard permissions assigned to your team (Admin, Editor, or Viewer).
> * Folder or dashboard permissions assigned to your user account (Admin, Editor, or Viewer).
> ...

https://grafana.com/docs/grafana/latest/permissions/

- [ ] create roles on Auth0
- [ ] enable grafana to refer to these roles

https://github.com/cloudnativedaysjp/dreamkast-infra/blob/b41fde066f1780c1b2af3e5a9cfc63b9dfb5dc32/manifests/argocd-apps/dev/grafana.yaml#L1501-L1515

**Comment by iaoiui** [comment]
下記ドキュメントによると、デフォルトでViewer roleが付与されるので実質的に一般参加者向けroleは現時点でもViewerが割当たっていそう。
https://grafana.com/docs/grafana/latest/auth/generic-oauth/#role-mapping

一方で現在の設定ではrole_attribute_strict = trueと設定してるので、明示的なroleが割当たっていない現状の一般参加者はアクセスが拒否されそう。

_- If  therole_attribute_path property does not return a role, then the user is assigned the Viewer role by default. You can disable the role assignment by setting role_attribute_strict = true. It denies user access if no role or an invalid role is returned._

role_attribute_strict = falseとすることのみで、viewer roleを暗黙的に渡すことで目的は達成出来るか

**Comment by kntks** [comment]
よかったら参考にしてください!

https://github.com/cloudnativedaysjp/dreamkast-infra/pull/988
