### ISSUE TITLE
Uptime robotをTerraform経由で設定出来るようにする

### ISSUE THREAD

**Issue by jacopen** [cloudnativedaysjp/dreamkast-infra#1313]
CloudWatchの外形監視は思ったよりもコストが高いため、より安価なUptime Robotに切り替えたい。

https://github.com/cloudnativedaysjp/dreamkast-infra/issues/1260

https://uptimerobot.com/

既にアカウントは作成済み。
Terraformの習熟を兼ねて、この設定をTerraformで行えるようにする

## タスク:
- [x] Uptime Robotのアカウント情報を共有 (jacopen)
- [x] Uptime RobotのAPIキーを発行(ry)
- [x] Uptime Robotの設定をTerraform化＆手元から反映(ry)
- [x] Terraform Cloudから実行出来るようにする(jacopen)

## 参考URL
https://qiita.com/akiko-pusu/items/c23fae93a1e2f41a04ad
https://registry.terraform.io/providers/louy/uptimerobot/latest/docs

## 設定すべき監視先
- https://cloudnativedays.jp
- https://event.cloudnativedays.jp

## 設定すべき内容
- 上記URLの監視
- Slackへの通知

## メモ
- 入れるべき設定に関しては、既存の設定(手動で追加したもの)を参考に
- ただし既存のUptime Robotの設定はそこまで重要ではないため、TF化の試行錯誤の過程で消してしまっても構わない

**Comment by jacopen** [comment]
それをやってしまうとk8s自体の障害の時に気づけないので、この話の代替にはならないですね。
外形監視は全く別の環境から行うべきなので。

もちろん、Observabilityチームで見る用のBlackbox Exporterを別途入れちゃうのは特に副作用無くやれるので、独自にやって貰うのは全然問題無いですー

**Comment by mhoshi-vm** [comment]
> それをやってしまうとk8s自体の障害の時に気づけないので、この話の代替にはならないですね。
外形監視は全く別の環境から行うべきなので。

まぁ、そのとおりですよね。
思っていたのが、外形監視もメトリクス化できればとおもっていましたが、了解です。別途こちらでやってしまいます。

**Comment by ryojsb** [comment]
```
╷
│ Error: Got error from UptimeRobot: {"message":"monitor already exists.","type":"already_exists"}
│
│   with uptimerobot_monitor.dreamkast,
│   on resource_dreamkast.tf line 2, in resource "uptimerobot_monitor" "dreamkast":
│    2: resource "uptimerobot_monitor" "dreamkast" {
│
╵
╷
│ Error: Got error from UptimeRobot: {"message":"monitor already exists.","type":"already_exists"}
│
│   with uptimerobot_monitor.website,
│   on resource_website.tf line 2, in resource "uptimerobot_monitor" "website":
│    2: resource "uptimerobot_monitor" "website" {
│
```

というように、既にMonitorがある場合にはじかれてしまうので、Issueで確認してみます。

**Comment by ryojsb** [comment]
# 手順メモ

## バイナリ入手
zipを落とす

https://github.com/louy/terraform-provider-uptimerobot/releases/tag/v0.5.1

## pluginの配置

```
$ unzip terraform-provider-uptimerobot_0.5.1_linux_amd64.zip
$ mkdir -p ~/.terraform.d/plugins/registry.terraform.io/hashicorp/uptimerobot/0.5.1/linux_amd64
$ cp -p terraform-provider-uptimerobot ~/.terraform.d/plugins/registry.terraform.io/hashicorp/uptimerobot/0.5.1/linux_amd64/
$ ls ~/.terraform.d/plugins/registry.terraform.io/hashicorp/uptimerobot/0.5.1/linux_amd64/
```

## varsを環境変数への適用

Credential情報のため、ファイルには書かないようにしている。

```
export TF_VAR_SLACK_WEBHOOK_URL='https://hooks.slack.com/services/******/******'
export TF_VAR_UPTIMEROBOT_API_KEY='******'
```

## terraformの実行

```
$ terraform init
$ terraform plan
$ terraform apply
```

**Comment by jacopen** [comment]
terraform cloud化完了したので終わり！
