### ISSUE TITLE
Add Blackbox monitoring

### ISSUE THREAD

**Issue by mhoshi-vm** [cloudnativedaysjp/dreamkast-infra#1316]
#1313 に関連して。
Blackboxのメトリクスをとれるようにしたい。やり方は

• Prometheus Blackbox Exporter
• TelegrafのHTTPプラグイン

**Comment by ryojsb** [comment]
下記を使用
https://github.com/prometheus-community/helm-charts/tree/main/charts/prometheus-blackbox-exporter

**Comment by ryojsb** [comment]
不要とのことなので、一旦Closeします。
