### ISSUE TITLE
AWSでBillingアラートを有効にする

### ISSUE THREAD

**Issue by kntks** [cloudnativedaysjp/dreamkast-infra#1330]
# 目的
Cloud Watchに請求のメトリクスを作れる状態にして、メトリクスを取得できるようにする

#1249 を進めるにあたってBillingのメトリクスが必要

# 現状
- バージニア北部でメトリクスを取得できていない
![スクリーンショット 2021-12-26 18 46 25](https://user-images.githubusercontent.com/24477226/147404560-a6d5fa6d-2b64-47e2-aa0a-70492f4449c1.png)
 
- rootアカウントではないため、Billingアラートを有効にできない
![スクリーンショット 2021-12-26 18 51 53](https://user-images.githubusercontent.com/24477226/147404683-90d9c4fd-d033-45aa-bb0f-da26d8d82f6a.png)

# 依頼
Billingアラートが有効になっているかの確認ともし有効になっていないならば有効にしてほしいです！

参考
https://engineer-ninaritai.com/cloudwatch-billing-alert/

**Comment by jyoshise** [comment]
有効になってなかったので有効にしました！

**Comment by kntks** [comment]
先ほど確認したらちゃんとメトリクス取れていました

ありがとうございます！
