### ISSUE TITLE
Grafana proposalダッシュボードにカテゴリのパネルがほしい

### ISSUE THREAD

**Issue by ureuzy** [cloudnativedaysjp/dreamkast-infra#1965]
CNDT2022 CFP選考会にてそういうフィードバックがあったので

**Comment by t4i5uKE** [comment]
https://github.com/cloudnativedaysjp/dreamkast/blob/f3c1b7993fe8f7ee9fdc35e11829cbdf9a39175c/db/fixtures/development/00_seeds.rb
