### ISSUE TITLE
CNDO2021のイベント終了後に各種リソースのスペックを落とす

### ISSUE THREAD

**Issue by takaishi** [cloudnativedaysjp/dreamkast-infra#328]
コスト圧縮

- RDS
- EKS
  - ノード台数とインスタンスタイプ
  - ECSなど低コストのプラットフォームに変更する手もある（ただし作ったDeliveryの仕組みが使えなくなる）
- CloudWatch
  - 外形監視も落とす
- prod/devの両環境確認する

**Comment by ShotaKitazawa** [comment]
dreamkast-dev-cluster EKS を落として、すべて dreamkast-cluster に寄せる

**Comment by takaishi** [comment]
@inductor に聞いたら終わっているとのことなので閉じます
