### ISSUE TITLE
Redisを冗長構成にする

### ISSUE THREAD

**Issue by inductor** [cloudnativedaysjp/dreamkast-infra#330]
今はチャレンジングになっている

**Comment by ShotaKitazawa** [comment]
メモ: https://github.com/spotahome/redis-operator 使おうとなってる

**Comment by inductor** [comment]
ElastiCacheでT4のGraviton instanceが対応されたので試してみる。これまではでかいインスタンスタイプしか選べないm6gを使っていたのでおおよそ1/3~1/6くらいのコストになっていることを期待

https://aws.amazon.com/jp/about-aws/whats-new/2021/11/amazon-elasticache-supports-t4g-graviton2-based-instances/?nc1=h_ls
