### ISSUE TITLE
ReviewAppのURLをPRにコメントするタイミングをArgoCDでSyncが完了したタイミングにできるとうれしい

### ISSUE THREAD

**Issue by takaishi** [cloudnativedaysjp/dreamkast-infra#351]
URLがコメントされたタイミングだとArgoCDのSyncが完了していなくて、アクセスできないということがあるのでArgoCD側でSync終わったタイミングにできるとうれしい。

**Comment by ShotaKitazawa** [comment]
reviewapp-operator の issue として以下に上がっているため、こちらの issue は閉じてしまいます。

https://github.com/cloudnativedaysjp/reviewapp-operator/issues/5
