### ISSUE TITLE
普段から可観測性を高めたい

### ISSUE THREAD

**Issue by ShotaKitazawa** [cloudnativedaysjp/dreamkast-infra#426]
「負荷がかかることが予想されるとき (イベント開催時) の可観測性を高めること」を目的に、以下をインストールする。
なお目的より想定される用途が「一時的に見れるダッシュボード」であるため、データの永続化は厳しすぎない程度にやる。

* Prometheus
* Grafana
* Loki

**Comment by ShotaKitazawa** [comment]
Grafana は以下の dashboard が欲しい

* dreamkast 監視 dashboard
  * 外形監視結果 (from AWS CloudWatch)
    * 正常なレスポンスが返ってきた割合
    * レイテンシ
  * dreamkast, dreamkast-ui の負荷 (from Prometheus)
    * load average

* dreamkast MySQL 監視 dashboard
  * 参考: https://ap-northeast-1.console.aws.amazon.com/cloudwatch/home?region=ap-northeast-1#dashboards:name=RDS (アカウント: 607167088920)

* NS 毎 (プルダウンで選択可能) の Pod 用 dashboard
  * Pod の負荷 (from Prometheus)
    * CPU, Mem, Disk I/O, Network I/O
  * Pod のログ (from Loki)

**Comment by ShotaKitazawa** [comment]
### 今後の方針

https://docs.google.com/document/d/1nkMH6gTKO_PQC5k5hkZk1xOS0evJn2r2pn35YFhzPhI/edit#heading=h.1jd3n26zwdpl より

* @oke-py さんが Prometheus, @kntks さんが Grafana を構築
* 成果物は dreamkast-infra リポジトリに PR
* Prometheus/Grafana 構築の deadline は 9 月頭
    * Loki も出来れば 9 月 (後述の検証用クラスタが 9 月までのため)
* 検証は検証用 EKS クラスタを利用する
    * 参考: https://cloudnativedays.slack.com/archives/C015CN1PQ06/p1623066695237200

**Comment by oke-py** [comment]
### contourのmetrics

- contour
  - namespace: projectcontour
  - name: deployment.apps/contour
  - path: pod:8000/metrics
- envoy
  - namespace: projectcontour
  - name: daemonset.apps/envoy
  - path: pod:8002/stats/prometheus

**Comment by oke-py** [comment]
### argocdのmetrics

- argocd-metrics
  - namespace: argocd
  - name: svc/argocd-metrics
  - path: pod:8002/metrics
- argocd-server-metrics
  - namespace: argocd
  - name: svc/argocd-server-metrics
  - path: pod:8003/metrics
- argocd-repo-server
  - namespace: argocd
  - name: svc/argocd-repo-server
  - path: pod:8004/metrics


argocd-dex-serverもmetricsをはいていそうですが、接続できませんでした。
```
k -n argocd port-forward svc/argocd-dex-server 5558 
Forwarding from 127.0.0.1:5558 -> 5558
Forwarding from [::1]:5558 -> 5558
Handling connection for 5558
E0702 21:53:47.782097   23815 portforward.go:400] an error occurred forwarding 5558 -> 5558: error forwarding port 5558 to pod 20fbd403312951faffe9324f10b1861a88cdc4473427df00eacb2f613d0215f6, uid : failed to execute portforward in network namespace "/var/run/netns/cni-9d3cddae-ac35-91de-0dc4-46a83052b277": failed to connect to localhost:5558 inside namespace "20fbd403312951faffe9324f10b1861a88cdc4473427df00eacb2f613d0215f6", IPv4: dial tcp4 127.0.0.1:5558: connect: connection refused IPv6 dial tcp6 [::1]:5558: connect: connection refused 
Handling connection for 5558
E0702 21:53:48.905747   23815 portforward.go:400] an error occurred forwarding 5558 -> 5558: error forwarding port 5558 to pod 20fbd403312951faffe9324f10b1861a88cdc4473427df00eacb2f613d0215f6, uid : failed to execute portforward in network namespace "/var/run/netns/cni-9d3cddae-ac35-91de-0dc4-46a83052b277": failed to connect to localhost:5558 inside namespace "20fbd403312951faffe9324f10b1861a88cdc4473427df00eacb2f613d0215f6", IPv4: dial tcp4 127.0.0.1:5558: connect: connection refused IPv6 dial tcp6 [::1]:5558: connect: connection refused 
Handling connection for 5558
E0702 21:53:54.013204   23815 portforward.go:400] an error occurred forwarding 5558 -> 5558: error forwarding port 5558 to pod 20fbd403312951faffe9324f10b1861a88cdc4473427df00eacb2f613d0215f6, uid : failed to execute portforward in network namespace "/var/run/netns/cni-9d3cddae-ac35-91de-0dc4-46a83052b277": failed to connect to localhost:5558 inside namespace "20fbd403312951faffe9324f10b1861a88cdc4473427df00eacb2f613d0215f6", IPv4: dial tcp4 127.0.0.1:5558: connect: connection refused IPv6 dial tcp6 [::1]:5558: connect: connection refused 
```

**Comment by oke-py** [comment]
#571 でLokiを入れました。

**Comment by oke-py** [comment]
> dreamkast MySQL 監視 dashboard

https://github.com/cloudnativedaysjp/dreamkast-infra/pull/725 で完了ですね。
https://grafana.dev.cloudnativedays.jp/ で確認しました。
https://grafana.cloudnativedays.jp/ ログインできない・・・:thinking:

**Comment by oke-py** [comment]
@ShotaKitazawa 使いこなせたかというと否ですが、ここで挙げられているダッシュボードは作成済みと思いますので、クローズしますか？

**Comment by ShotaKitazawa** [comment]
しましょう！対応ありがとうございます！！これから自分も使いこなしていこうと思います！！
