### ISSUE TITLE
[oke-py] dreamkast-infraのローカル開発環境を構築する

### ISSUE THREAD

**Issue by oke-py** [cloudnativedaysjp/dreamkast-infra#438]
## 概要

Prometheusなどのデプロイ検証を進めるために、dreamkast-infraのローカル開発環境を構築する。

**Comment by oke-py** [comment]
EKSのバージョンを確認します。blob指定のURLを載せておきますが、環境構築するときはmainブランチを参照します。
https://github.com/cloudnativedaysjp/dreamkast-infra/blob/8eab5de/cfn/eks.yaml#L52

現在は1.18を利用していることがわかったので、1.18でkind clusterを作成します。
```
kind create cluster --image kindest/node:v1.18.19
```

argocdを使っていきますが、namespaceは作成済みの前提っぽいです。
```
kubectl create ns argocd
```

argocdをデプロイします。

```
cd manifests/argocd
kustomize build overlays/development | kubectl apply -f - 
```

argocdのadminパスワードを取得します。
```
kubectl -n argocd get secret argocd-initial-admin-secret -o jsonpath='{.data.password}' | base64 -d  
```

```
kubectl -n argocd port-forward svc/argocd-server 8443:443
```

localhost:8443 にアクセスして admin:<さきほどのパスワード> でログインします。

**Comment by inductor** [comment]
@oke-py あー、CFnはそうなってるけど、バージョンはCFnでは管理して無くて今は1.20で動いてます

**Comment by oke-py** [comment]
お、了解ですー
