### ISSUE TITLE
Review appsのNamespaceが残ってしまう

### ISSUE THREAD

**Issue by jacopen** [cloudnativedaysjp/dreamkast-infra#46]
ArgoCDで上手く消えてくれない･･･

**Comment by ShotaKitazawa** [comment]
メモ
* ArgoCD Application 側で `spec.syncPolicy.syncOptions[0]: CreateNamespace=true` を指定するのではなく、デプロイ対象のマニフェストの中に Namespace リソースの宣言があれば pruning 時に namespace も delete される説 (未検証)

**Comment by ShotaKitazawa** [comment]
> ArgoCD Application 側で spec.syncPolicy.syncOptions[0]: CreateNamespace=true を指定するのではなく、デプロイ対象のマニフェストの中に Namespace リソースの宣言があれば pruning 時に namespace も delete される説 (未検証)

これで消えることを確認しました。

reviewapp-operator 導入と同時に ArgoCD から ns.yaml をデプロイするようにしたため、対応済みです。
