### ISSUE TITLE
Releasebotが重複している

### ISSUE THREAD

**Issue by jacopen** [cloudnativedaysjp/dreamkast-infra#777]
![image](https://user-images.githubusercontent.com/79102/133297048-483a66c5-1c71-4f57-964d-e4117e180e8e.png)
![image (15)](https://user-images.githubusercontent.com/79102/133297070-7a8e02b8-fa3a-4706-8635-dd7c91711b5c.png)

両方にReleasebotが動いているので反応が重複してしまう様子。

どちらのクラスタに設置するか決めた上で修正する

**Comment by jacopen** [comment]
個人的には安定稼働しているのはProdのほうなので、Prodのほうがいいかなーという気はしている。他にも意見あればplz

**Comment by ShotaKitazawa** [comment]
自分も prod 派ですー
dev に置いちゃうと「dev クラスタだから立て直しちゃえ」が安易にできなくなっちゃう欠点があると思ってます

**Comment by jacopen** [comment]
ArgoCDみるとProd側にReview appsが残っているのでそちらも対処が必要かも
